#!/bin/sh
# UTF backend configuration — interactive backend selection using bsddialog.
#
# Usage:
#   sh configure.sh          # interactive selection, then build
#   sh configure.sh --build  # build immediately after selection
#   sh configure.sh --show   # show current configuration without building
#
# Writes selected options to .config in the UTF root directory.
# build.sh and install.sh read .config automatically if present.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/.config"
BUILD=0
SHOW=0

# ============================================================================
# Argument parsing
# ============================================================================

for arg in "$@"; do
    case "$arg" in
        --build) BUILD=1 ;;
        --show)  SHOW=1  ;;
        --help|-h)
            sed -n '2,10p' "$0" | sed 's/^# \?//'
            exit 0 ;;
    esac
done

# ============================================================================
# Show current config
# ============================================================================

if [ "$SHOW" -eq 1 ]; then
    if [ -f "$CONFIG" ]; then
        echo "Current configuration ($CONFIG):"
        cat "$CONFIG"
    else
        echo "No configuration file found. Run: sh configure.sh"
    fi
    exit 0
fi

# ============================================================================
# Check for bsddialog
# ============================================================================

if ! command -v bsddialog >/dev/null 2>&1; then
    echo "bsddialog not found — falling back to plain text menu."
    echo ""
    echo "Select backends to enable (y/n):"
    printf "  Vulkan (requires vulkan-headers, vulkan-loader) [y/N]: "; read -r WANT_VULKAN
    printf "  X11 (requires libX11) [y/N]: "; read -r WANT_X11
    printf "  Wayland (requires libwayland-client) [y/N]: "; read -r WANT_WAYLAND
    printf "  bsdinput / libinput (requires libinput, libudev-devd) [y/N]: "; read -r WANT_BSDINPUT

    case "$WANT_VULKAN"  in [yY]) VULKAN=true  ;; *) VULKAN=false  ;; esac
    case "$WANT_X11"     in [yY]) X11=true     ;; *) X11=false     ;; esac
    case "$WANT_WAYLAND" in [yY]) WAYLAND=true ;; *) WAYLAND=false ;; esac
    case "$WANT_BSDINPUT" in [yY]) BSDINPUT=true ;; *) BSDINPUT=false ;; esac
else

# ============================================================================
# bsddialog checklist
# ============================================================================

TMPFILE=$(mktemp /tmp/utf-config.XXXXXX)
trap 'rm -f $TMPFILE' EXIT

bsddialog \
    --title "UTF Backend Configuration" \
    --checklist "Select the semadraw backends to enable.\n\nVulkan and bsdinput require additional packages.\nX11 and Wayland require a display server.\nThe software and drawfs backends are always included.\n\nUse SPACE to toggle, ENTER to confirm." \
    0 0 0 \
    "vulkan"   "Vulkan (requires vulkan-headers, vulkan-loader)"  off \
    "x11"      "X11 (requires libX11)"                            off \
    "wayland"  "Wayland (requires libwayland-client)"             off \
    "bsdinput" "bsdinput (requires libinput, libudev-devd)"       off \
    2>"$TMPFILE" || {
        echo "Cancelled."
        exit 0
    }

SELECTED=$(cat "$TMPFILE")

VULKAN=false; X11=false; WAYLAND=false; BSDINPUT=false

for item in $SELECTED; do
    case "$item" in
        vulkan)   VULKAN=true   ;;
        x11)      X11=true      ;;
        wayland)  WAYLAND=true  ;;
        bsdinput) BSDINPUT=true ;;
    esac
done

fi # end bsddialog block

# ============================================================================
# Write config
# ============================================================================

cat > "$CONFIG" << EOF
# UTF build configuration — generated by configure.sh on $(date)
# Edit manually or re-run: sh configure.sh
SEMADRAW_VULKAN=$VULKAN
SEMADRAW_X11=$X11
SEMADRAW_WAYLAND=$WAYLAND
SEMADRAW_BSDINPUT=$BSDINPUT
EOF

echo ""
echo "Configuration saved to $CONFIG:"
cat "$CONFIG"
echo ""

# ============================================================================
# Optionally build
# ============================================================================

if [ "$BUILD" -eq 1 ]; then
    sh "$SCRIPT_DIR/build.sh"
fi

echo "To build:   sh build.sh"
echo "To install: sh install.sh"
